### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by atillabirer** [abrkn/bitcoin-json-rpc#5]
On a node with no rpcuser or rpcpassword (it works with litecoin-cli), I am getting an "401 unauthorized" error.

The library also seems to lack facility to set JSON-RPC user and password.

**Comment by MrHash** [comment]
it is possible to use credentials on the url in the format `<protocol>://<username>:<password>@<host>:<port>`

**Comment by atillabirer** [comment]
> it is possible to use credentials on the url in the format `<protocol>://<username>:<password>@<host>:<port>`

Ok, thank you. Are you guys planning to write documentation?

**Comment by abrkn** [comment]
> > it is possible to use credentials on the url in the format `<protocol>://<username>:<password>@<host>:<port>`
> 
> Ok, thank you. Are you guys planning to write documentation?

We're open for PRs if you'd like to
